name: Windows RDP con Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configurar Escritorio Remoto (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Crear Usuario y Contraseña Segura
        run: |
          $Password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 14 | ForEach-Object {[char]$_})
          net user /add Runner $Password
          net localgroup administrators Runner /add
          echo "RDP_PASSWORD=$Password" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Instalar y Conectar Tailscale
        uses: tailscale/github-action@v2
        with:
          # Reemplace la siguiente línea con su clave de autenticación real de Tailscale.
          # Asegúrese de mantener las comillas.
          authkey: "tskey-auth-SU-CLAVE-AQUI"

      - name: Mostrar Credenciales de Conexión
        run: |
          echo "--- CREDENCIALES DE ACCESO RDP ---"
          echo "Dirección IP (PC Name): $(tailscale ip -4)"
          echo "Usuario: Runner"
          echo "Contraseña: ${{ env.RDP_PASSWORD }}"
          echo "----------------------------------"

      - name: Mantener la Conexión Activa
        run: Start-Sleep -Seconds 21600
